server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #配置Nacos地址
        server-addr: 192.168.109.128:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'